python_sources(
    dependencies=[
        ":settings"
    ]
)

python_source(
    name="settings",
    source="settings.py",
    dependencies=[
        "//:reqs#psycopg2-binary",
        "//:reqs#python-decouple",
    ]
)
